### ISSUE TITLE
Resetting settings?

### ISSUE THREAD

**Issue by Aircl0wn** [FuzzyIdeas/YellowDot#2]
First time starting all went fine, and it looked like the app was doing a good job!
So, I hid the menu bar icon, but now I can't open up the GUI any more?

The usual approach of reopening the app while running doesn't open the interface either. 
I have to manually killall it to quit. 
Removing it with it's produced plist and reinstalling it doesn't reset the settings either?

**Comment by alin23** [comment]
Opening the app launches the window as expected:

https://user-images.githubusercontent.com/3819725/148570718-2ae6463c-bb0d-4279-9b64-4e351334ccf9.mp4

Have you checked if the window isn't on another space? It seems that for me, macOS always opens the window on a specific space no matter what space is visible.

Anyway, resetting the settings can be done with the following commands:

```sh
pkill -9 -fl YellowDot
rm ~/Library/Preferences/com.lowtechguys.YellowDot.plist
```

**Comment by Aircl0wn** [comment]
It's not doing that for me at all. The only time I've seen the UI was the very first time I launched it.
I've already tried it with deleting the mentioned plist file and even replacing the app with a fresh download (giving the usual warning popup). 
It's starting the process, but it's not showing me the UI any more.

**Comment by alin23** [comment]
Try:

```sh
pkill -9 -fl YellowDot
defaults write com.lowtechguys.YellowDot hideMenubarIcon 0
```

Then launch the app again

**Comment by Aircl0wn** [comment]
That worked. The UI shows up again.
