### ISSUE TITLE
Multi-monitor and hiding the dot

### ISSUE THREAD

**Issue by Aircl0wn** [FuzzyIdeas/YellowDot#3]
I've got a multi-monitor setup: m1 + 2 external screens.
Upon starting the app, it removes all the dots. 
When I tab through apps and get to different screens, it's only hiding the dot on the screen with the active display, which is I believe the default behaviour?

**Comment by alin23** [comment]
Quoting from #1

> In case your confusion is about the Control Center icon dot:
> 
> 
> 
> YellowDot only hides the corner dot as exemplified here:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/3819725/148093515-2aa757ad-f06c-4633-956b-f5ce0c81623d.png)
> 
> 
> 
> The Control Panel icon dot can't be hidden as it's embedded inside the icon.
> 
> 
> 
> <img width="42" alt="image" src="https://user-images.githubusercontent.com/3819725/148093631-4b0c4f57-6f3d-40be-ba65-037fb3373916.png">
> 
> 
> 
> Hiding the corner dot is what's most needed because that dot doesn't go away when the menubar is not visible.

On my M1 Macbook with 1 external display and 1 Sidecar, the corner dot is hidden from all displays as expected.

**Comment by Aircl0wn** [comment]
I understand it's only the fat dot that's removed.

On initial start of the application, it's removing it on all three screen. But after selecting an app on one screen, it shows again on the others. Going to an app on a different screen, that one is removed, but the previous screen now has a dot again.

**Comment by alin23** [comment]
The system is constantly showing the dots, and the YellowDot app is constantly hiding them. 

There's no way to permanently remove the dot, but you can make the app remove the dots faster using this setting:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/3819725/148593724-cf8429f3-fe23-41b7-86b0-e0a5961def86.png">

**Comment by Aircl0wn** [comment]
I noticed that setting on the first run but couldn't test it. Now that that is resolved, I'll try this out when I'm back at my desk.

**Comment by Aircl0wn** [comment]
It is indeed working fine! 
It seems that because I couldn't get to the interface, it was still paused? Maybe from the very first session.
It probably hides the dot on start-up anyway but wasn't updating be because it was paused (I had to click start).
Now it's working nicely!
