### ISSUE TITLE
V2 mentions that it is for macOS 12.2, but it is compiled for 13.0+

### ISSUE THREAD

**Issue by guibarrette** [FuzzyIdeas/YellowDot#7]
The new version 2 of YellowDot mentions that it is for use on macOS 12.2 and above. However, the compiled application has a minimal macOS version of 13.0 and above. Therefore, it can't be opened on macOS 12.2...

**Comment by alin23** [comment]
Indeed, I should fix that. I forgot I used macOS 13 APIs. Thanks!
