### ISSUE TITLE
Wide gamut color space - HDR - Bright dot

### ISSUE THREAD

**Issue by imkebe** [FuzzyIdeas/YellowDot#9]
There is an issue with the wide color gamut screens. While the app does apply the brightness filter - it should be done with respect to the wide color gamut color profiles.
Setting the brightness = 1.0 for a SDR screen looks ok - the menubar icons have the same color value ~ looks like the same brightness.
Setting the brightness = 1.0 for a SDR screen gives the dot higher than default UI items brightness ~ it's glowing.

I have 4 screens. Two of them are HDR (including internal MacBook one). Two of them are SDR based. It's not easy to show not having the HDR capable screen.

**Comment by alin23** [comment]
Unfortunately a lower brightness would keep the dot semi-coloured. It's not possible to make this a less bright white.

![Copy Merged](https://github.com/FuzzyIdeas/YellowDot/assets/3819725/d8ad8924-04c5-4492-a33c-06d7504bf754)

I could use a 0.75 value for HDR displays to avoid the glowing effect, but it is no longer pure white.

**Comment by imkebe** [comment]
Is there a way to apply filter to get the color unsaturated ?

**Comment by alin23** [comment]
No, there is no way. The brightness function is the only one that's still working on the dot window.

**Comment by alin23** [comment]
I tested the `0.5` to `0.99` values and the dot is still a bit glowing because its yellow/orange color is already at the highest luminance. So whatever we put in, it will exceed the highest SDR brightness.

I'll keep it as is for now, because having it even a bit coloured is more distracting than having a glowing white.
